-- generated by gemini

CREATE TABLE IF NOT EXISTS users
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
-- Name fields
    full_name  TEXT NOT NULL,

    bday       TEXT, -- Store as TEXT (YYYY-MM-DD format)
    gender     TEXT,

    email      TEXT NOT NULL UNIQUE,
    phone      TEXT,

    address    TEXT,
    city       TEXT,
    states     TEXT,
    postcode   TEXT,

    university TEXT,
    profession TEXT,
    password TEXT
)
